# Generated by Django 3.2.8 on 2021-11-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_manageorder_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageorder',
            name='payment',
            field=models.CharField(choices=[('C', 'CashOnDelivery'), ('P', 'Paid')], default='P', max_length=1),
        ),
    ]
