# Generated by Django 3.2.8 on 2021-11-12 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_manageorder_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManageOrder',
        ),
    ]
