# Generated by Django 3.2.8 on 2021-11-12 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_manageorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Processing'), ('S', 'Shipping'), ('D', 'Delivered'), ('R', 'Refunded')], default='P', max_length=1)),
                ('payment', models.CharField(choices=[('C', 'CashOnDelivery'), ('P', 'Paid')], default='P', max_length=1)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.order')),
            ],
        ),
    ]
